// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxpVb6rY9zL_tMKbdRVj8OS6AmliZtaq8',
    appId: '1:250572354728:web:ed3739de81cdd09151fe9d',
    messagingSenderId: '250572354728',
    projectId: 'mafqud-15648',
    authDomain: 'mafqud-15648.firebaseapp.com',
    storageBucket: 'mafqud-15648.appspot.com',
    measurementId: 'G-MRVRHJVN9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9YRajEdTaUGPGyk-HMP1e9WGg03rItnc',
    appId: '1:250572354728:android:235cb3ab1095bb2f51fe9d',
    messagingSenderId: '250572354728',
    projectId: 'mafqud-15648',
    storageBucket: 'mafqud-15648.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY1U_k6aSSbsJoTqG84uAvgPeCnUvs4cw',
    appId: '1:250572354728:ios:2fe1501aed1ba0a551fe9d',
    messagingSenderId: '250572354728',
    projectId: 'mafqud-15648',
    storageBucket: 'mafqud-15648.appspot.com',
    iosBundleId: 'com.example.mafqud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY1U_k6aSSbsJoTqG84uAvgPeCnUvs4cw',
    appId: '1:250572354728:ios:2fe1501aed1ba0a551fe9d',
    messagingSenderId: '250572354728',
    projectId: 'mafqud-15648',
    storageBucket: 'mafqud-15648.appspot.com',
    iosBundleId: 'com.example.mafqud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxpVb6rY9zL_tMKbdRVj8OS6AmliZtaq8',
    appId: '1:250572354728:web:94dc60575bd54e2051fe9d',
    messagingSenderId: '250572354728',
    projectId: 'mafqud-15648',
    authDomain: 'mafqud-15648.firebaseapp.com',
    storageBucket: 'mafqud-15648.appspot.com',
    measurementId: 'G-0XRRX3FP39',
  );
}
